spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crypto_simulation?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always


server:
  port: 8080

logging:
  level:
    org.springframework.jdbc.core: DEBUG
